# Generated by Django 4.2 on 2023-05-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
